<?php

namespace home\loginBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * testTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userRepository extends EntityRepository
{
}
